/* =============================================================
   Premier Herbal Inc. — Product Data
   All products available for wholesale ordering.
   ============================================================= */

const ALL_PRODUCTS = [
  { title: "Acacia Catechu", uses: ["Ayurvedic", "Medicinal"], form: "Cut Sifted" },
  { title: "Acai Berry", uses: ["Antioxidant", "Supplement"], form: "Whole" },
  { title: "Accacia Berry Juice Powder", uses: ["Antioxidant", "Supplement"], form: "Powder" },
  { title: "Acerola Berry- 25%", uses: ["Supplement", "Vitamin C"], form: "Powder" },
  { title: "Activated Charcoal", uses: ["Detox", "Supplement"], form: "Powder" },
  { title: "African Chili Bird Pepper", uses: ["Culinary", "Spice"], form: "Powder" },
  { title: "Agrimony Herb", uses: ["Digestive", "Medicinal"], form: "Whole" },
  { title: "Ajawan Seed", uses: ["Culinary", "Digestive"], form: "Whole" },
  { title: "Alfaalfa Seed", uses: ["Culinary", "Supplement"], form: "Whole" },
  { title: "Alfalfa Lvs", uses: ["Supplement", "Tea"], form: "Whole" },
  { title: "Allspice", uses: ["Culinary", "Spice"], form: "Whole" },
  { title: "Aloe Vera", uses: ["Digestive", "Skincare"], form: "Whole" },
  { title: "Amla", uses: ["Ayurvedic", "Antioxidant"], form: "Whole" },
  { title: "Angelica Root", uses: ["Digestive", "Medicinal"], form: "Cut Sifted" },
  { title: "Angilica Seed", uses: ["Digestive", "Medicinal"], form: "Whole" },
  { title: "Anise Seed", uses: ["Culinary", "Digestive"], form: "Whole" },
  { title: "Anise Star", uses: ["Culinary", "Digestive"], form: "Whole" },
  { title: "Annamu Leaf", uses: ["Medicinal"], form: "Whole" },
  { title: "Annato Seed", uses: ["Culinary", "Spice"], form: "Whole" },
  { title: "Apple Cider Vinegar", uses: ["Digestive", "Supplement"], form: "Powder" },
  { title: "Arjuna Terminalia", uses: ["Ayurvedic", "Heart Health"], form: "Cut Sifted" },
  { title: "Arnica Flower", uses: ["Skincare", "Topical"], form: "Whole" },
  { title: "Artichoke Leaves", uses: ["Digestive", "Liver"], form: "Whole" },
  { title: "Asafoetida Pieces", uses: ["Culinary", "Digestive"], form: "Whole" },
  { title: "Ascorbic Acid", uses: ["Supplement", "Vitamin C"], form: "Powder" },
  { title: "Ash Bark", uses: ["Medicinal"], form: "Cut Sifted" },
  { title: "Ashwagandha", uses: ["Adaptogen", "Ayurvedic"], form: "Cut Sifted" },
  { title: "Astragulus Root", uses: ["Adaptogen", "Immunity"], form: "Cut Sifted" },
  { title: "Balm Lemon Herb", uses: ["Calming", "Tea"], form: "Whole" },
  { title: "Balm of Gilead Buds", uses: ["Skincare", "Topical"], form: "Whole" },
  { title: "Barley Grass", uses: ["Detox", "Supplement"], form: "Whole" },
  { title: "Basil Leaves", uses: ["Culinary", "Herb"], form: "Whole" },
  { title: "Bay Leaves", uses: ["Culinary", "Spice"], form: "Whole" },
  { title: "Bayberry Bark", uses: ["Medicinal"], form: "Cut Sifted" },
  { title: "Bean Pods, Fava", uses: ["Culinary"], form: "Whole" },
  { title: "Bearberry Leaf", uses: ["Medicinal", "Urinary"], form: "Whole" },
  { title: "Beet Root", uses: ["Supplement", "Detox"], form: "Powder" },
  { title: "Bilberry", uses: ["Antioxidant", "Eye Health"], form: "Whole" },
  { title: "Birch Leaf", uses: ["Detox", "Medicinal"], form: "Whole" },
  { title: "Bitter Melon", uses: ["Blood Sugar", "Supplement"], form: "Whole" },
  { title: "Black Cohosh Root", uses: ["Womens Health", "Medicinal"], form: "Cut Sifted" },
  { title: "Black Cumin Seed", uses: ["Culinary", "Immunity"], form: "Whole" },
  { title: "Black Pepper", uses: ["Culinary", "Spice"], form: "Whole" },
  { title: "Black Walnut Hull", uses: ["Antiparasitic", "Medicinal"], form: "Cut Sifted" },
  { title: "Blackberry Leaf", uses: ["Tea", "Medicinal"], form: "Whole" },
  { title: "Blessed Thistle", uses: ["Digestive", "Medicinal"], form: "Whole" },
  { title: "Blue Cohosh Root", uses: ["Womens Health", "Medicinal"], form: "Cut Sifted" },
  { title: "Blue Vervain", uses: ["Calming", "Nervous System"], form: "Whole" },
  { title: "Boldo Leaf", uses: ["Digestive", "Liver"], form: "Whole" },
  { title: "Boneset Herb", uses: ["Immunity", "Medicinal"], form: "Whole" },
  { title: "Borage Herb", uses: ["Skincare", "Supplement"], form: "Whole" },
  { title: "Boswellia", uses: ["Anti Inflammatory", "Joint Health"], form: "Cut Sifted" },
  { title: "Brindle Berry", uses: ["Weight Loss", "Supplement"], form: "Whole" },
  { title: "Broom Tops", uses: ["Medicinal", "Heart Health"], form: "Whole" },
  { title: "Buchu Leaf", uses: ["Urinary", "Medicinal"], form: "Whole" },
  { title: "Burdock Root", uses: ["Detox", "Liver"], form: "Cut Sifted" },
  { title: "Butchers Broom", uses: ["Circulation", "Medicinal"], form: "Cut Sifted" },
  { title: "Calendula Flower", uses: ["Skincare", "Topical"], form: "Whole" },
  { title: "Camellia Sinensis Leaf", uses: ["Tea", "Antioxidant"], form: "Whole" },
  { title: "Capsicum", uses: ["Culinary", "Spice"], form: "Powder" },
  { title: "Caraway Seed", uses: ["Culinary", "Digestive"], form: "Whole" },
  { title: "Cardamom", uses: ["Culinary", "Digestive"], form: "Whole" },
  { title: "Cascara Sagrada", uses: ["Laxative", "Digestive"], form: "Cut Sifted" },
  { title: "Catnip Herb", uses: ["Calming", "Tea"], form: "Whole" },
  { title: "Cats Claw Bark", uses: ["Immunity", "Anti Inflammatory"], form: "Cut Sifted" },
  { title: "Cayenne 40K", uses: ["Culinary", "Spice"], form: "Powder" },
  { title: "Celery Seed", uses: ["Culinary", "Digestive"], form: "Whole" },
  { title: "Centaury Herb", uses: ["Digestive", "Medicinal"], form: "Whole" },
  { title: "Chamomile Flower", uses: ["Calming", "Tea"], form: "Whole" },
  { title: "Chaparral Herb", uses: ["Antioxidant", "Medicinal"], form: "Whole" },
  { title: "Chaste Berry", uses: ["Womens Health", "Supplement"], form: "Whole" },
  { title: "Chickweed Herb", uses: ["Skincare", "Medicinal"], form: "Whole" },
  { title: "Chicory Root", uses: ["Digestive", "Prebiotic"], form: "Cut Sifted" },
  { title: "Chuchuhuasi Bark", uses: ["Anti Inflammatory", "Medicinal"], form: "Cut Sifted" },
  { title: "Cilantro Leaf", uses: ["Culinary", "Herb"], form: "Whole" },
  { title: "Cinnamon", uses: ["Culinary", "Spice"], form: "Powder" },
  { title: "Cleavers Herb", uses: ["Detox", "Medicinal"], form: "Whole" },
  { title: "Clove", uses: ["Culinary", "Spice"], form: "Whole" },
  { title: "Coffee Leaf", uses: ["Tea", "Energy"], form: "Whole" },
  { title: "Cola Nut", uses: ["Energy", "Supplement"], form: "Whole" },
  { title: "Coltsfoot Herb", uses: ["Respiratory", "Medicinal"], form: "Whole" },
  { title: "Comfrey Herb", uses: ["Topical", "Medicinal"], form: "Whole" },
  { title: "Coriander", uses: ["Culinary", "Spice"], form: "Whole" },
  { title: "Corn Silk", uses: ["Urinary", "Medicinal"], form: "Whole" },
  { title: "Cornflower", uses: ["Skincare", "Tea"], form: "Whole" },
  { title: "Couch Grass", uses: ["Urinary", "Medicinal"], form: "Cut Sifted" },
  { title: "Cramp Bark", uses: ["Womens Health", "Medicinal"], form: "Cut Sifted" },
  { title: "Cranberry", uses: ["Urinary", "Antioxidant"], form: "Whole" },
  { title: "Cubeb Berries", uses: ["Culinary", "Spice"], form: "Whole" },
  { title: "Cumin", uses: ["Culinary", "Digestive"], form: "Whole" },
  { title: "Damiana Herb", uses: ["Mood", "Medicinal"], form: "Whole" },
  { title: "Dandelion Leaf", uses: ["Detox", "Digestive"], form: "Whole" },
  { title: "Dandelion Root", uses: ["Liver", "Digestive"], form: "Cut Sifted" },
  { title: "Devils Claw Root", uses: ["Anti Inflammatory", "Joint Health"], form: "Cut Sifted" },
  { title: "Dill Seed", uses: ["Culinary", "Digestive"], form: "Whole" },
  { title: "Dong Quai Root", uses: ["Womens Health", "Ayurvedic"], form: "Cut Sifted" },
  { title: "Dulse Leaf", uses: ["Supplement", "Thyroid"], form: "Whole" },
  { title: "Echinacea Angustifolia Root", uses: ["Immunity", "Medicinal"], form: "Cut Sifted" },
  { title: "Echinacea Purpurea Herb", uses: ["Immunity", "Medicinal"], form: "Whole" },
  { title: "Elderberry", uses: ["Immunity", "Antioxidant"], form: "Whole" },
  { title: "Elderflower", uses: ["Tea", "Skincare"], form: "Whole" },
  { title: "Elecampane Root", uses: ["Respiratory", "Medicinal"], form: "Cut Sifted" },
  { title: "Eleuthero Root", uses: ["Adaptogen", "Energy"], form: "Cut Sifted" },
  { title: "Eucalyptus Leaf", uses: ["Respiratory", "Medicinal"], form: "Whole" },
  { title: "Evening Primrose", uses: ["Womens Health", "Skincare"], form: "Whole" },
  { title: "Eyebright Herb", uses: ["Eye Health", "Medicinal"], form: "Whole" },
  { title: "False Unicorn Root", uses: ["Womens Health", "Medicinal"], form: "Cut Sifted" },
  { title: "Fennel Seed", uses: ["Culinary", "Digestive"], form: "Whole" },
  { title: "Fenugreek Seed", uses: ["Culinary", "Supplement"], form: "Whole" },
  { title: "Feverfew Herb", uses: ["Migraine", "Anti Inflammatory"], form: "Whole" },
  { title: "Fo-Ti Root", uses: ["Ayurvedic", "Supplement"], form: "Cut Sifted" },
  { title: "Fringe Tree Bark", uses: ["Liver", "Medicinal"], form: "Cut Sifted" },
  { title: "Fumitory Herb", uses: ["Liver", "Digestive"], form: "Whole" },
  { title: "Galangal Root", uses: ["Culinary", "Digestive"], form: "Cut Sifted" },
  { title: "Garlic", uses: ["Culinary", "Immunity"], form: "Powder" },
  { title: "Gentian Root", uses: ["Digestive", "Bitters"], form: "Cut Sifted" },
  { title: "Ginger Root", uses: ["Culinary", "Digestive"], form: "Cut Sifted" },
  { title: "Ginkgo Biloba Leaf", uses: ["Brain Health", "Circulation"], form: "Whole" },
  { title: "Ginseng Root", uses: ["Adaptogen", "Energy"], form: "Cut Sifted" },
  { title: "Globe Artichoke", uses: ["Digestive", "Liver"], form: "Whole" },
  { title: "Goats Rue Herb", uses: ["Blood Sugar", "Medicinal"], form: "Whole" },
  { title: "Goldenseal Root", uses: ["Immunity", "Medicinal"], form: "Cut Sifted" },
  { title: "Gotu Kola Herb", uses: ["Brain Health", "Skincare"], form: "Whole" },
  { title: "Gravel Root", uses: ["Urinary", "Medicinal"], form: "Cut Sifted" },
  { title: "Green Tea Leaf", uses: ["Tea", "Antioxidant"], form: "Whole" },
  { title: "Grindelia Herb", uses: ["Respiratory", "Medicinal"], form: "Whole" },
  { title: "Guarana Seed", uses: ["Energy", "Supplement"], form: "Powder" },
  { title: "Gymnema Sylvestre", uses: ["Blood Sugar", "Supplement"], form: "Whole" },
  { title: "Hawthorn Berry", uses: ["Heart Health", "Antioxidant"], form: "Whole" },
  { title: "Hawthorn Leaf & Flower", uses: ["Heart Health", "Medicinal"], form: "Whole" },
  { title: "He Shou Wu", uses: ["Ayurvedic", "Haircare"], form: "Cut Sifted" },
  { title: "Hibiscus Flower", uses: ["Tea", "Antioxidant"], form: "Whole" },
  { title: "Holy Basil Leaf", uses: ["Adaptogen", "Ayurvedic"], form: "Whole" },
  { title: "Hops Flower", uses: ["Sleep", "Calming"], form: "Whole" },
  { title: "Horehound Herb", uses: ["Respiratory", "Medicinal"], form: "Whole" },
  { title: "Horse Chestnut", uses: ["Circulation", "Medicinal"], form: "Cut Sifted" },
  { title: "Horsetail Herb", uses: ["Haircare", "Supplement"], form: "Whole" },
  { title: "Hyssop Herb", uses: ["Respiratory", "Digestive"], form: "Whole" },
  { title: "Irish Moss", uses: ["Thyroid", "Supplement"], form: "Whole" },
  { title: "Jamaican Dogwood Bark", uses: ["Pain Relief", "Medicinal"], form: "Cut Sifted" },
  { title: "Juniper Berry", uses: ["Urinary", "Culinary"], form: "Whole" },
  { title: "Kava Kava Root", uses: ["Calming", "Anxiety"], form: "Cut Sifted" },
  { title: "Kelp", uses: ["Thyroid", "Supplement"], form: "Whole" },
  { title: "Kudzu Root", uses: ["Supplement", "Medicinal"], form: "Cut Sifted" },
  { title: "Lavender Flower", uses: ["Calming", "Skincare"], form: "Whole" },
  { title: "Lemon Grass", uses: ["Culinary", "Tea"], form: "Whole" },
  { title: "Licorice Root", uses: ["Digestive", "Ayurvedic"], form: "Cut Sifted" },
  { title: "Linden Flower", uses: ["Calming", "Tea"], form: "Whole" },
  { title: "Lions Mane Mushroom", uses: ["Brain Health", "Supplement"], form: "Powder" },
  { title: "Lobelia Herb", uses: ["Respiratory", "Medicinal"], form: "Whole" },
  { title: "Maca Root", uses: ["Energy", "Supplement"], form: "Powder" },
  { title: "Maitake Mushroom", uses: ["Immunity", "Supplement"], form: "Whole" },
  { title: "Manjistha Root", uses: ["Ayurvedic", "Skincare"], form: "Cut Sifted" },
  { title: "Marjoram Leaf", uses: ["Culinary", "Herb"], form: "Whole" },
  { title: "Marshmallow Root", uses: ["Digestive", "Respiratory"], form: "Cut Sifted" },
  { title: "Meadowsweet Herb", uses: ["Digestive", "Anti Inflammatory"], form: "Whole" },
  { title: "Milk Thistle Seed", uses: ["Liver", "Antioxidant"], form: "Whole" },
  { title: "Mistletoe Herb", uses: ["Heart Health", "Medicinal"], form: "Whole" },
  { title: "Motherwort Herb", uses: ["Womens Health", "Heart Health"], form: "Whole" },
  { title: "Mugwort Herb", uses: ["Digestive", "Medicinal"], form: "Whole" },
  { title: "Mullein Leaf", uses: ["Respiratory", "Medicinal"], form: "Whole" },
  { title: "Mustard Seed Black", uses: ["Culinary", "Spice"], form: "Whole" },
  { title: "Mustard Seed Yellow", uses: ["Culinary", "Spice"], form: "Whole" },
  { title: "Myrrh Gum", uses: ["Topical", "Incense"], form: "Cut Sifted" },
  { title: "Neem Leaf", uses: ["Skincare", "Ayurvedic"], form: "Whole" },
  { title: "Nettle Leaf", uses: ["Anti Inflammatory", "Tea"], form: "Whole" },
  { title: "Nutmeg", uses: ["Culinary", "Spice"], form: "Powder" },
  { title: "Oat Straw", uses: ["Nervous System", "Supplement"], form: "Cut Sifted" },
  { title: "Olive Leaf", uses: ["Antioxidant", "Immunity"], form: "Whole" },
  { title: "Onion Flakes", uses: ["Culinary", "Spice"], form: "Cut Sifted" },
  { title: "Oregano Leaf", uses: ["Culinary", "Herb"], form: "Whole" },
  { title: "Oregon Grape Root", uses: ["Digestive", "Liver"], form: "Cut Sifted" },
  { title: "Papaya Leaf", uses: ["Digestive", "Supplement"], form: "Whole" },
  { title: "Paprika", uses: ["Culinary", "Spice"], form: "Powder" },
  { title: "Parsley Leaf", uses: ["Culinary", "Herb"], form: "Whole" },
  { title: "Passion Flower Herb", uses: ["Calming", "Sleep"], form: "Whole" },
  { title: "Pau D Arco Bark", uses: ["Immunity", "Medicinal"], form: "Cut Sifted" },
  { title: "Peppercorn Black", uses: ["Culinary", "Spice"], form: "Whole" },
  { title: "Peppermint Leaf", uses: ["Digestive", "Tea"], form: "Whole" },
  { title: "Periwinkle Herb", uses: ["Brain Health", "Circulation"], form: "Whole" },
  { title: "Plantain Herb", uses: ["Respiratory", "Topical"], form: "Whole" },
  { title: "Pleurisy Root", uses: ["Respiratory", "Medicinal"], form: "Cut Sifted" },
  { title: "Pomegranate Peel", uses: ["Antioxidant", "Supplement"], form: "Cut Sifted" },
  { title: "Poppy Seed", uses: ["Culinary", "Spice"], form: "Whole" },
  { title: "Prickly Ash Bark", uses: ["Circulation", "Medicinal"], form: "Cut Sifted" },
  { title: "Psyllium Husk", uses: ["Digestive", "Prebiotic"], form: "Whole" },
  { title: "Pygeum Bark", uses: ["Mens Health", "Supplement"], form: "Cut Sifted" },
  { title: "Red Clover Herb", uses: ["Womens Health", "Supplement"], form: "Whole" },
  { title: "Red Raspberry Leaf", uses: ["Womens Health", "Tea"], form: "Whole" },
  { title: "Rehmannia Root", uses: ["Ayurvedic", "Supplement"], form: "Cut Sifted" },
  { title: "Reishi Mushroom", uses: ["Immunity", "Adaptogen"], form: "Cut Sifted" },
  { title: "Rhodiola Root", uses: ["Adaptogen", "Energy"], form: "Cut Sifted" },
  { title: "Rose Hip", uses: ["Vitamin C", "Antioxidant"], form: "Whole" },
  { title: "Rose Petals", uses: ["Skincare", "Tea"], form: "Whole" },
  { title: "Rosemary Leaf", uses: ["Culinary", "Herb"], form: "Whole" },
  { title: "Sage Leaf", uses: ["Culinary", "Herb"], form: "Whole" },
  { title: "Sarsaparilla Root", uses: ["Detox", "Supplement"], form: "Cut Sifted" },
  { title: "Saw Palmetto Berry", uses: ["Mens Health", "Supplement"], form: "Whole" },
  { title: "Schisandra Berry", uses: ["Adaptogen", "Liver"], form: "Whole" },
  { title: "Senna Leaf", uses: ["Laxative", "Digestive"], form: "Whole" },
  { title: "Shavegrass Herb", uses: ["Supplement", "Haircare"], form: "Whole" },
  { title: "Sheep Sorrel", uses: ["Detox", "Medicinal"], form: "Whole" },
  { title: "Shiitake Mushroom", uses: ["Immunity", "Supplement"], form: "Whole" },
  { title: "Skullcap Herb", uses: ["Calming", "Nervous System"], form: "Whole" },
  { title: "Slippery Elm Bark", uses: ["Digestive", "Respiratory"], form: "Powder" },
  { title: "Spearmint Leaf", uses: ["Culinary", "Tea"], form: "Whole" },
  { title: "Spirulina", uses: ["Supplement", "Detox"], form: "Powder" },
  { title: "St. Johns Wort", uses: ["Mood", "Medicinal"], form: "Whole" },
  { title: "Stevia Leaf", uses: ["Sweetener", "Supplement"], form: "Whole" },
  { title: "Suma Root", uses: ["Adaptogen", "Energy"], form: "Cut Sifted" },
  { title: "Sumac Berry", uses: ["Culinary", "Antioxidant"], form: "Whole" },
  { title: "Tansy", uses: ["Antiparasitic", "Medicinal"], form: "Whole" },
  { title: "Tarragon", uses: ["Culinary", "Digestive"], form: "Whole" },
  { title: "Thyme Leaves", uses: ["Culinary", "Herb"], form: "Whole" },
  { title: "Tomato", uses: ["Culinary", "Supplement"], form: "Whole" },
  { title: "Tonka Beans", uses: ["Culinary", "Incense"], form: "Whole" },
  { title: "Triphla Pwd.", uses: ["Ayurvedic", "Detox"], form: "Powder" },
  { title: "Tulsi Leaves (Holy Basil)", uses: ["Adaptogen", "Ayurvedic"], form: "Whole" },
  { title: "Turmeric", uses: ["Culinary", "Anti Inflammatory"], form: "Cut Sifted" },
  { title: "Unsea Lichen", uses: ["Immunity", "Respiratory"], form: "Whole" },
  { title: "Uva Ursi Leaves", uses: ["Urinary", "Anti Inflammatory"], form: "Whole" },
  { title: "Valarian Root", uses: ["Sleep", "Calming"], form: "Cut Sifted" },
  { title: "Vervain Blue", uses: ["Calming", "Nervous System"], form: "Whole" },
  { title: "Violet Herb", uses: ["Skincare", "Respiratory"], form: "Whole" },
  { title: "Watercrest", uses: ["Culinary", "Supplement"], form: "Whole" },
  { title: "Wheat Grass", uses: ["Detox", "Energy"], form: "Whole" },
  { title: "White Pine Bark", uses: ["Antioxidant", "Respiratory"], form: "Cut Sifted" },
  { title: "White Sage Leaves", uses: ["Incense", "Topical"], form: "Whole" },
  { title: "White Willow Bark", uses: ["Anti Inflammatory", "Pain Relief"], form: "Cut Sifted" },
  { title: "Wild Cherry Bark", uses: ["Respiratory", "Medicinal"], form: "Cut Sifted" },
  { title: "Wild Yam Root", uses: ["Womens Health", "Anti Inflammatory"], form: "Cut Sifted" },
  { title: "Winter Green Leaves", uses: ["Pain Relief", "Topical"], form: "Whole" },
  { title: "Witch Hazel Leaves", uses: ["Skincare", "Anti Inflammatory"], form: "Whole" },
  { title: "Wood Betony", uses: ["Digestive", "Nervous System"], form: "Whole" },
  { title: "Wood Sage", uses: ["Digestive", "Medicinal"], form: "Whole" },
  { title: "Woodruff", uses: ["Calming", "Medicinal"], form: "Whole" },
  { title: "Wormwood", uses: ["Antiparasitic", "Digestive"], form: "Whole" },
  { title: "Yarrow Flower", uses: ["Anti Inflammatory", "Womens Health"], form: "Whole" },
  { title: "Yellow Dock Root", uses: ["Detox", "Liver"], form: "Cut Sifted" },
  { title: "Yerba Mate Green", uses: ["Energy", "Tea"], form: "Whole" },
  { title: "Yerba Santa", uses: ["Respiratory", "Medicinal"], form: "Whole" },
  { title: "Yohimbe Bark", uses: ["Mens Health", "Supplement"], form: "Cut Sifted" },
  { title: "Yucca Root", uses: ["Anti Inflammatory", "Joint Health"], form: "Cut Sifted" },
  { title: "Zizyphus Seed", uses: ["Sleep", "Calming"], form: "Whole" }
];
